from __future__ import annotations

import json
import re

from app.services.llm_service import get_llm


RAW_FILE_RULES = """
REPOSITORY FILE CONTENT RULES:

Repository file contents may be supplied under "repository_files".

When repository_files contains the target file, that supplied file
content is the authoritative current state of that file.

For change_type="modify":

1. proposed_change.before MUST be an exact substring copied verbatim
   from the supplied repository file.

2. proposed_change.after MUST contain the exact replacement text.

3. Do NOT use descriptive placeholders as the "before" value.

Examples of invalid before values:

- "Unknown"
- "current configuration"
- "dependency_count: 0"
- "plugin must be added"
- "dependency is currently vulnerable"
- "existing dependency configuration"
- "no securityContext defined"

4. If an exact before/after replacement cannot be constructed from
   supplied repository file contents, do not include the change in the
   executable changes array.

5. Never claim that a dependency, plugin, property, annotation,
   class, method, configuration value, or other code element exists
   unless supplied repository evidence proves it.

For change_type="create":

1. The target path must not already exist in the complete repository
   path inventory.

2. proposed_change.before MUST be null.

3. proposed_change.after MUST contain the COMPLETE UTF-8 text content
   that should be written to the new file.

4. An intentionally empty placeholder file such as .gitkeep may use
   an empty string for proposed_change.after.

5. Do not create files merely because they are conventional.
   Creation must be supported by the modernization plan and repository
   evidence.

For change_type="delete":

1. The target file must exist in repository_files.

2. Deletion must be explicitly justified by repository evidence.

3. proposed_change.before must contain exact existing file content.

4. proposed_change.after must be null.

VERSION RULE:

Do not invent dependency, plugin, framework, runtime, or tool versions.

Exact versions may only be used when they are supported by trusted
repository/scanner evidence supplied in the context.

Recommendations generated by other language-model agents are not
authoritative evidence for exact dependency or plugin versions.

Do not introduce a new library version merely because you know a
commonly used version from general knowledge.

PATCH QUALITY RULE:

Prefer the smallest exact textual change that resolves the evidenced
issue.

A proposed automated modification must be mechanically applicable from
the supplied before and after values without requiring interpretation
or guessing.

SAME FILE ATOMIC PATCH RULE:

When multiple proposed automated changes target the same existing file:

1. Prefer ONE combined atomic change for that file.

2. The combined proposed_change.before must be copied from the ORIGINAL
   repository file content supplied in repository_files.

3. proposed_change.after must represent the complete replacement for
   that exact original section.

4. Never create a sequence where one change's before value depends on
   another proposed change's after value.

5. Every modify change must be independently applicable to the ORIGINAL
   repository state.

6. If several modifications cannot be represented as independent,
   non-overlapping replacements against the original file, consolidate
   them into ONE modification.

EXECUTABLE CHANGE ONLY RULE:

The "changes" array is an executable patch proposal.

Do NOT include a change when any required value is unresolved.

If a dependency version, plugin version, framework version, SHA,
configuration value, credential, secret, or implementation decision
cannot be established from supplied evidence:

- do not create a placeholder patch
- do not invent a realistic-looking value
- omit the change from the executable changes array

Never emit placeholder values such as:

- VERIFY_VERSION
- TODO
- TBD
- UNKNOWN
- RESOLVE_SHA
- CHOOSE_VERSION
- REPLACE_ME
- INSERT_VALUE
- PLACEHOLDER

Every item in "changes" must have:

- automation_candidate=true
- verification_required=false
"""


SECURITY_PRIORITY_RULES = """
SECURITY REMEDIATION PRIORITY RULES:

You MUST perform security prioritization BEFORE selecting lower-priority
modernization changes.

Follow this order:

1. Confirmed CRITICAL vulnerability remediation.
2. Confirmed HIGH vulnerability remediation.
3. Confirmed security configuration findings with deterministic fixes.
4. MEDIUM security hardening.
5. LOW security hardening.
6. Non-security modernization.

Do NOT stop after finding a convenient set of medium or low severity
changes.

Do NOT arbitrarily limit the proposal to three changes.

Before proposing Kubernetes, Docker, style, maintainability, or other
lower-priority work, inspect vulnerability_analysis for every confirmed
CRITICAL and HIGH vulnerability.

For each CRITICAL or HIGH vulnerable dependency, determine whether a
safe executable dependency patch can be produced.

A dependency upgrade may be proposed only when ALL of these are true:

1. The vulnerable package coordinate is confirmed by dependency or
   vulnerability scanner evidence.

2. The currently resolved vulnerable version is confirmed by scanner
   evidence.

3. A fixed version is explicitly supplied by trusted vulnerability
   scanner evidence.

4. The repository file containing the relevant dependency declaration
   is supplied in repository_files.

5. An exact mechanically applicable before/after replacement can be
   created from that file.

6. The remediation does not require guessing a parent framework,
   platform, BOM, plugin, or unrelated dependency version.

DIRECT DEPENDENCY VERSION OVERRIDE RULE:

If a vulnerable dependency is directly declared in a supplied build
file but its version is omitted because dependency management currently
controls it, an explicit fixed version MAY be proposed only when:

- the exact dependency coordinate is present in the build file,
- vulnerability scanner evidence supplies the exact fixed version,
- the dependency is confirmed as direct,
- the patch changes only that dependency declaration,
- no other framework/BOM version has to be guessed.

Treat such an override as at least medium risk and require human
approval.

TRANSITIVE DEPENDENCY SAFETY RULE:

If a vulnerable dependency is transitive:

- do NOT invent a direct dependency override,
- do NOT guess a Spring Boot version,
- do NOT guess a BOM version,
- do NOT guess a parent version,
- do NOT guess which upstream dependency controls it.

A transitive vulnerability should be omitted from executable changes
unless the repository itself contains an existing, directly evidenced
version property or declaration that safely controls that dependency.

UNRESOLVED CRITICAL/HIGH ISSUE RULE:

If a CRITICAL or HIGH finding cannot be safely automated, do not invent
a patch just to address it.

Instead:

- omit it from "changes",
- mention it in the proposal summary,
- mention that it remains unresolved,
- include human verification/remediation in validation_steps.

The existence of an unresolved critical finding does not authorize an
unsafe patch.

CREDENTIAL AND SECRET SAFETY RULE:

Never invent or generate:

- passwords
- API keys
- access tokens
- database credentials
- private keys
- secret values

If a repository contains an empty or weak password, that is valid
evidence of a problem but NOT evidence for what the replacement secret
should be.

Do NOT automatically replace an empty password with a made-up password.

Do NOT invent an environment-variable name solely to make the patch
executable.

Credential remediation belongs in the executable changes array only if
the exact replacement mechanism/value is already supported by supplied
repository evidence.

Otherwise omit it and describe it as requiring human verification.

SECURITY CONFIGURATION RULE:

For static-analysis findings such as Kubernetes securityContext changes,
the exact configuration value may be proposed only when the scanner rule
itself explicitly supplies the required deterministic value or when the
required value is already supported by repository/scanner evidence.

A scanner finding that says:

allowPrivilegeEscalation must be false

can support:

allowPrivilegeEscalation: false

A scanner finding that says:

runAsNonRoot must be true

does NOT by itself prove that the referenced container image can run as
a non-root user.

Do not automate a newly introduced:

runAsNonRoot: true

unless supplied raw repository evidence already establishes compatible
non-root execution for that container image.

If compatibility is not established, omit runAsNonRoot from the
executable patch and leave it for human verification.

A deterministic scanner finding may still support:

allowPrivilegeEscalation: false

when that exact required value is explicitly supplied by scanner
evidence.

Do not generalize this permission to unrelated security settings.

PRIORITIZATION EXAMPLE:

If repository evidence contains:

- CRITICAL dependency vulnerability with trusted fixed version
- HIGH dependency vulnerability with trusted fixed version
- MEDIUM Kubernetes securityContext issue

and all three can be safely patched,

the dependency vulnerabilities MUST be proposed before the Kubernetes
hardening change.

If a critical transitive dependency cannot safely be patched because
the controlling version is unknown, omit that unsafe patch and continue
with other evidence-complete fixes.
"""


SYSTEM_PROMPT = """
You are the Code Agent for CodeShift AI.

Your job is to convert a modernization plan into a structured
set of proposed repository changes.

You are NOT allowed to directly modify repository files.

You must only propose changes.

Use ONLY evidence explicitly present in the supplied repository context.

Do not use your general knowledge as evidence.

Do not invent:

- files that do not exist
- file contents that were not supplied
- dependencies that were not detected
- vulnerabilities that were not detected
- framework versions not present in trusted evidence
- source-code usage that was not detected
- annotations that were not detected
- logging patterns that were not detected
- configuration values that were not detected
- GitHub Action commit SHAs
- dependency versions not present in trusted evidence
- plugin versions not present in trusted evidence
- library versions based only on model knowledge
- passwords
- credentials
- secret values

IMPORTANT EVIDENCE RULE:

Every statement placed inside the evidence array must be directly
traceable to information contained in the supplied repository context.

Generated technical-debt recommendations, architecture prose, and
modernization-plan recommendations may describe desired work, but they
do NOT prove exact dependency versions, plugin versions, SHAs, or
existing repository contents.

Exact technical values must come from repository or scanner evidence.

GITHUB ACTION RULE:

Never invent or guess commit SHAs.

A GitHub Action commit SHA is trusted only when the exact 40-character
SHA already appears in raw repository file content supplied under
repository_files.files.

Scanner prose, Semgrep recommendations, technical-debt findings,
architecture prose, modernization-plan prose, and Code Agent output do
NOT establish a trusted GitHub Action SHA.

If the exact SHA is not already present in raw repository file content,
omit the SHA-pinning change from the executable changes array.

TRANSITIVE DEPENDENCY RULE:

A vulnerable transitive dependency does not prove which parent,
framework, BOM, or plugin version must be upgraded.

Do not invent a parent or framework version.

IMPORTANT ATOMIC PATCH RULE:

Do not produce cascading modifications to the same file.

Every before value must apply to the ORIGINAL repository state.

If several dependent modifications affect one file, merge them into one
atomic change.

IMPORTANT VERSION SAFETY RULE:

Do not choose JUnit, Mockito, AssertJ, SLF4J, Logback, Maven plugin,
JaCoCo, Spring Boot, framework, or other dependency versions from
general knowledge.

If the exact version is not present in trusted repository/scanner
evidence, omit that patch.

IMPORTANT EXECUTABLE PROPOSAL RULE:

The changes array must contain only concrete, evidence-complete changes.

Do not include unresolved recommendations.

Never place placeholder or guessed values in proposed_change.before or
proposed_change.after.

Prefer the smallest safe change necessary.

Return ONLY valid JSON.

Required output format:

{
  "summary": "short description of proposed changes and important unresolved security findings",
  "change_count": 0,
  "changes": [
    {
      "file": "relative/path/to/file",
      "change_type": "modify | create | delete",
      "title": "short change title",
      "reason": "why this change is needed",
      "evidence": [
        "only directly supported repository evidence"
      ],
      "risk": "low | medium | high",
      "automation_candidate": true,
      "verification_required": false,
      "proposed_change": {
        "description": "what should change",
        "before": "exact existing text, null for create",
        "after": "exact replacement or complete new file content"
      }
    }
  ],
  "tests_to_run": [
    "specific test/build command"
  ],
  "validation_steps": [
    "validation step"
  ],
  "requires_human_approval": true
}

Rules:

1. Do not modify files directly.

2. Do not generate destructive changes.

3. Do not delete files unless strongly supported by evidence.

4. Security fixes must be prioritized by demonstrated severity.

5. Confirmed CRITICAL and HIGH vulnerability remediations must be
   considered before MEDIUM or LOW hardening changes.

6. Dependency upgrades must cite detected dependency and vulnerability
   evidence.

7. If the exact repository file is unknown, do not guess the path.

8. If a change requires architectural judgment, omit it from changes.

9. Always require human approval.

10. Preserve existing application behavior whenever possible.

11. Propose incremental changes instead of rewrites.

12. Evidence must come from supplied context, not model knowledge.

13. Do not infer vulnerable feature usage from dependency presence.

14. Never invent exact versions, SHAs, paths, annotations, APIs,
    configuration values, code usage, credentials, or secrets.

15. If an exact remediation value cannot be established, omit the
    change.

16. Do not include verification_required=true changes.

17. Do not include automation_candidate=false changes.

18. A transitive dependency finding does not prove a direct dependency.

19. Do not claim exploitability unless supplied evidence establishes it.

20. Never produce cascading same-file modifications.

21. Every modify operation must apply to the original repository state.

22. Never invent versions simply to make a patch executable.

23. Recommendations from other LLM agents are not trusted evidence for
    exact versions.

24. Do not stop after identifying a fixed number of changes.

25. Include every evidence-complete CRITICAL or HIGH remediation that
    can be safely automated before selecting lower-severity work.

26. If a CRITICAL or HIGH issue cannot be safely automated, disclose
    that limitation in summary and validation_steps rather than creating
    an unsafe patch.

27. Never create a password or secret replacement from model knowledge.

""" + SECURITY_PRIORITY_RULES + RAW_FILE_RULES


PLACEHOLDER_MARKERS = (
    "VERIFY_",
    "TODO",
    "TBD",
    "UNKNOWN",
    "RESOLVE_SHA",
    "CHOOSE_VERSION",
    "REPLACE_ME",
    "INSERT_VALUE",
    "PLACEHOLDER",
)


SENSITIVE_CREDENTIAL_TERMS = (
    "password",
    "passwd",
    "credential",
    "secret",
    "api key",
    "api_key",
    "access token",
    "access_token",
    "private key",
    "private_key",
)


VERSION_TAG_PATTERN = re.compile(
    r"""
    <
    (?P<tag>
        version
        |
        [A-Za-z0-9_.-]*version
    )
    >
    \s*
    (?P<value>
        [0-9]+
        (?:\.[0-9A-Za-z_-]+)+
    )
    \s*
    </
    (?P=tag)
    >
    """,
    re.VERBOSE | re.IGNORECASE,
)


GITHUB_ACTION_SHA_PATTERN = re.compile(
    r"@[0-9a-fA-F]{40}\b"
)


def _contains_placeholder(
    value: object,
) -> bool:

    if not isinstance(
        value,
        str,
    ):
        return False

    upper_value = value.upper()

    return any(
        marker in upper_value
        for marker in PLACEHOLDER_MARKERS
    )


def _touches_sensitive_credentials(
    change: dict,
) -> bool:
    """
    Credential and secret mutations are intentionally excluded
    from automated CodeShift patches.

    A finding may prove that an insecure credential exists, but that
    does not provide evidence for the replacement secret.
    """

    evidence = change.get(
        "evidence",
        [],
    )

    evidence_text = ""

    if isinstance(
        evidence,
        list,
    ):
        evidence_text = " ".join(
            str(item)
            for item in evidence
        )

    proposed_change = change.get(
        "proposed_change",
        {},
    )

    description = ""

    if isinstance(
        proposed_change,
        dict,
    ):
        description = str(
            proposed_change.get(
                "description",
                "",
            )
        )

    combined_text = " ".join(
        [
            str(
                change.get(
                    "title",
                    "",
                )
            ),
            str(
                change.get(
                    "reason",
                    "",
                )
            ),
            evidence_text,
            description,
        ]
    ).lower()

    return any(
        term in combined_text
        for term in SENSITIVE_CREDENTIAL_TERMS
    )


def _trusted_version_evidence(
    repository_context: dict,
) -> str:

    trusted_context = {
        "repository_files": (
            repository_context.get(
                "repository_files",
                {},
            )
        ),
        "dependency_analysis": (
            repository_context.get(
                "dependency_analysis",
                {},
            )
        ),
        "vulnerability_analysis": (
            repository_context.get(
                "vulnerability_analysis",
                {},
            )
        ),
        "semgrep_analysis": (
            repository_context.get(
                "semgrep_analysis",
                {},
            )
        ),
        "java_version": (
            repository_context.get(
                "java_version"
            )
        ),
        "build_tools": (
            repository_context.get(
                "build_tools",
                [],
            )
        ),
        "frameworks": (
            repository_context.get(
                "frameworks",
                [],
            )
        ),
    }

    return json.dumps(
        trusted_context,
        default=str,
    )


def _introduced_unverified_versions(
    before: object,
    after: object,
    trusted_evidence: str,
) -> list[str]:

    if not isinstance(
        after,
        str,
    ):
        return []

    before_text = (
        before
        if isinstance(
            before,
            str,
        )
        else ""
    )

    before_versions = {
        match.group(
            "value"
        )
        for match in VERSION_TAG_PATTERN.finditer(
            before_text
        )
    }

    after_versions = {
        match.group(
            "value"
        )
        for match in VERSION_TAG_PATTERN.finditer(
            after
        )
    }

    introduced = (
        after_versions
        - before_versions
    )

    return sorted(
        version
        for version in introduced
        if version
        not in trusted_evidence
    )


def _trusted_github_sha_evidence(
    repository_context: dict,
) -> str:
    """
    Return only raw repository file content for GitHub Action SHA trust.

    Scanner/model prose is deliberately excluded.
    """

    repository_files = repository_context.get(
        "repository_files",
        {},
    )

    if not isinstance(
        repository_files,
        dict,
    ):
        return ""

    file_entries = repository_files.get(
        "files",
        [],
    )

    if not isinstance(
        file_entries,
        list,
    ):
        return ""

    contents = []

    for entry in file_entries:

        if not isinstance(
            entry,
            dict,
        ):
            continue

        content = entry.get(
            "content"
        )

        if isinstance(
            content,
            str,
        ):
            contents.append(
                content
            )

    return "\n".join(
        contents
    )


def _introduces_run_as_non_root(
    before: object,
    after: object,
) -> bool:
    """
    New runAsNonRoot=true settings require image compatibility evidence.
    """

    if not isinstance(
        after,
        str,
    ):
        return False

    before_text = (
        before
        if isinstance(
            before,
            str,
        )
        else ""
    )

    pattern = re.compile(
        r"(?im)^\s*runAsNonRoot\s*:\s*true\s*$"
    )

    return (
        bool(
            pattern.search(
                after
            )
        )
        and not bool(
            pattern.search(
                before_text
            )
        )
    )


def _introduced_unverified_github_shas(
    before: object,
    after: object,
    trusted_evidence: str,
) -> list[str]:

    if not isinstance(
        after,
        str,
    ):
        return []

    before_text = (
        before
        if isinstance(
            before,
            str,
        )
        else ""
    )

    before_shas = {
        match.group(0)[1:]
        for match in GITHUB_ACTION_SHA_PATTERN.finditer(
            before_text
        )
    }

    after_shas = {
        match.group(0)[1:]
        for match in GITHUB_ACTION_SHA_PATTERN.finditer(
            after
        )
    }

    introduced = (
        after_shas
        - before_shas
    )

    return sorted(
        sha
        for sha in introduced
        if sha not in trusted_evidence
    )


async def create_code_change_proposal(
    repository_context: dict,
) -> dict:

    llm = get_llm()

    prompt = (
        SYSTEM_PROMPT
        + "\n\nRepository context:\n"
        + json.dumps(
            repository_context,
            indent=2,
            default=str,
        )
    )

    response = await llm.ainvoke(
        prompt
    )

    content = response.content

    if isinstance(
        content,
        list,
    ):
        text_parts = []

        for item in content:

            if isinstance(
                item,
                dict,
            ):
                text_value = item.get(
                    "text"
                )

                if text_value:
                    text_parts.append(
                        text_value
                    )

            else:
                text_parts.append(
                    str(item)
                )

        content = "".join(
            text_parts
        )

    content = str(
        content
    ).strip()

    if content.startswith(
        "```json"
    ):
        content = content[
            len("```json"):
        ]

    elif content.startswith(
        "```"
    ):
        content = content[
            len("```"):
        ]

    if content.endswith(
        "```"
    ):
        content = content[:-3]

    content = content.strip()

    try:
        result = json.loads(
            content
        )

    except json.JSONDecodeError as exc:
        raise RuntimeError(
            "Code Agent returned invalid JSON."
        ) from exc

    if not isinstance(
        result,
        dict,
    ):
        raise RuntimeError(
            "Code Agent returned an invalid "
            "response structure."
        )

    changes = result.get(
        "changes"
    )

    if not isinstance(
        changes,
        list,
    ):
        raise RuntimeError(
            "Code Agent response is missing "
            "a valid changes list."
        )

    result[
        "requires_human_approval"
    ] = True

    repository_files = (
        repository_context.get(
            "repository_files",
            {},
        )
    )

    repository_file_entries = []
    all_paths = []
    inventory_complete = False

    if isinstance(
        repository_files,
        dict,
    ):
        repository_file_entries = (
            repository_files.get(
                "files",
                [],
            )
        )

        all_paths = (
            repository_files.get(
                "all_paths",
                [],
            )
        )

        inventory_complete = bool(
            repository_files.get(
                "inventory_complete",
                False,
            )
        )

    if not isinstance(
        all_paths,
        list,
    ):
        all_paths = []

    repository_path_set = {
        path
        for path in all_paths
        if isinstance(
            path,
            str,
        )
    }

    repository_file_map = {}

    if isinstance(
        repository_file_entries,
        list,
    ):

        for entry in repository_file_entries:

            if not isinstance(
                entry,
                dict,
            ):
                continue

            path = entry.get(
                "path"
            )

            file_content = entry.get(
                "content"
            )

            if (
                isinstance(
                    path,
                    str,
                )
                and isinstance(
                    file_content,
                    str,
                )
            ):
                repository_file_map[
                    path
                ] = file_content

    trusted_evidence = (
        _trusted_version_evidence(
            repository_context
        )
    )

    trusted_github_sha_evidence = (
        _trusted_github_sha_evidence(
            repository_context
        )
    )

    modify_changes_by_file = {}

    for index, change in enumerate(
        changes
    ):

        if not isinstance(
            change,
            dict,
        ):
            continue

        change_type = change.get(
            "change_type"
        )

        file_path = change.get(
            "file"
        )

        proposed_change = change.get(
            "proposed_change"
        )

        if not isinstance(
            proposed_change,
            dict,
        ):
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

            continue

        before = proposed_change.get(
            "before"
        )

        after = proposed_change.get(
            "after"
        )

        if (
            change.get(
                "verification_required",
                False,
            )
            or not change.get(
                "automation_candidate",
                False,
            )
        ):
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

        # -------------------------------------------------
        # Deterministic credential safety gate.
        #
        # CodeShift may identify credential problems, but it
        # must not automatically invent replacement secrets.
        # -------------------------------------------------

        if _touches_sensitive_credentials(
            change
        ):
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

        if (
            _contains_placeholder(
                before
            )
            or _contains_placeholder(
                after
            )
        ):
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

        unverified_versions = (
            _introduced_unverified_versions(
                before,
                after,
                trusted_evidence,
            )
        )

        if unverified_versions:
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

            change[
                "_unverified_versions"
            ] = unverified_versions

        unverified_github_shas = (
            _introduced_unverified_github_shas(
                before,
                after,
                trusted_github_sha_evidence,
            )
        )

        if unverified_github_shas:
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

            change[
                "_unverified_github_shas"
            ] = unverified_github_shas

        if _introduces_run_as_non_root(
            before,
            after,
        ):
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

            change[
                "_run_as_non_root_requires_verification"
            ] = True

        if change_type == "create":

            proposed_change[
                "before"
            ] = None

            if not isinstance(
                after,
                str,
            ):
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

            if (
                not isinstance(
                    file_path,
                    str,
                )
                or not file_path
            ):
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

            elif not inventory_complete:
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

            elif (
                file_path
                in repository_path_set
            ):
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

        elif change_type == "modify":

            invalid_patch = False

            if (
                not isinstance(
                    before,
                    str,
                )
                or not before
                or not isinstance(
                    after,
                    str,
                )
            ):
                invalid_patch = True

            if (
                not isinstance(
                    file_path,
                    str,
                )
                or not file_path
                or file_path
                not in repository_file_map
            ):
                invalid_patch = True

            elif (
                isinstance(
                    before,
                    str,
                )
                and repository_file_map[
                    file_path
                ].count(
                    before
                )
                != 1
            ):
                invalid_patch = True

            if invalid_patch:
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

            if isinstance(
                file_path,
                str,
            ):
                modify_changes_by_file.setdefault(
                    file_path,
                    [],
                ).append(
                    index
                )

        elif change_type == "delete":

            proposed_change[
                "after"
            ] = None

            if not isinstance(
                before,
                str,
            ):
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

            if (
                not isinstance(
                    file_path,
                    str,
                )
                or not file_path
                or file_path
                not in repository_file_map
            ):
                change[
                    "automation_candidate"
                ] = False

                change[
                    "verification_required"
                ] = True

        else:
            change[
                "automation_candidate"
            ] = False

            change[
                "verification_required"
            ] = True

    # -----------------------------------------------------
    # Validate multiple modifications to the same file.
    #
    # Every modification must apply independently against
    # the ORIGINAL file and must not overlap another patch.
    # -----------------------------------------------------

    for (
        file_path,
        indexes,
    ) in modify_changes_by_file.items():

        if len(
            indexes
        ) <= 1:
            continue

        original_content = (
            repository_file_map.get(
                file_path
            )
        )

        if not isinstance(
            original_content,
            str,
        ):

            for index in indexes:
                changes[index][
                    "automation_candidate"
                ] = False

                changes[index][
                    "verification_required"
                ] = True

            continue

        before_values = []
        unsafe_group = False

        for index in indexes:

            patch = changes[
                index
            ].get(
                "proposed_change",
                {},
            )

            before = (
                patch.get(
                    "before"
                )
                if isinstance(
                    patch,
                    dict,
                )
                else None
            )

            if (
                not isinstance(
                    before,
                    str,
                )
                or not before
                or original_content.count(
                    before
                )
                != 1
            ):
                unsafe_group = True
                break

            before_values.append(
                before
            )

        if not unsafe_group:

            for first_index in range(
                len(
                    before_values
                )
            ):

                first = (
                    before_values[
                        first_index
                    ]
                )

                first_start = (
                    original_content.find(
                        first
                    )
                )

                first_end = (
                    first_start
                    + len(
                        first
                    )
                )

                for second_index in range(
                    first_index + 1,
                    len(
                        before_values
                    ),
                ):

                    second = (
                        before_values[
                            second_index
                        ]
                    )

                    second_start = (
                        original_content.find(
                            second
                        )
                    )

                    second_end = (
                        second_start
                        + len(
                            second
                        )
                    )

                    overlaps = not (
                        first_end
                        <= second_start
                        or second_end
                        <= first_start
                    )

                    if overlaps:
                        unsafe_group = True
                        break

                if unsafe_group:
                    break

        if unsafe_group:

            for index in indexes:
                changes[index][
                    "automation_candidate"
                ] = False

                changes[index][
                    "verification_required"
                ] = True

    executable_changes = []

    for change in changes:

        if not isinstance(
            change,
            dict,
        ):
            continue

        if change.get(
            "verification_required",
            False,
        ):
            continue

        if not change.get(
            "automation_candidate",
            False,
        ):
            continue

        # Recheck credential safety before allowing a
        # proposal into the executable output.
        if _touches_sensitive_credentials(
            change
        ):
            continue

        proposed_change = change.get(
            "proposed_change"
        )

        if not isinstance(
            proposed_change,
            dict,
        ):
            continue

        before = proposed_change.get(
            "before"
        )

        after = proposed_change.get(
            "after"
        )

        if (
            _contains_placeholder(
                before
            )
            or _contains_placeholder(
                after
            )
        ):
            continue

        if _introduced_unverified_versions(
            before,
            after,
            trusted_evidence,
        ):
            continue

        if _introduced_unverified_github_shas(
            before,
            after,
            trusted_github_sha_evidence,
        ):
            continue

        if _introduces_run_as_non_root(
            before,
            after,
        ):
            continue

        change_type = change.get(
            "change_type"
        )

        file_path = change.get(
            "file"
        )

        if (
            not isinstance(
                file_path,
                str,
            )
            or not file_path
        ):
            continue

        if change_type == "modify":

            if (
                file_path
                not in repository_file_map
            ):
                continue

            if (
                not isinstance(
                    before,
                    str,
                )
                or not before
            ):
                continue

            if not isinstance(
                after,
                str,
            ):
                continue

            if (
                repository_file_map[
                    file_path
                ].count(
                    before
                )
                != 1
            ):
                continue

        elif change_type == "create":

            if not inventory_complete:
                continue

            if (
                file_path
                in repository_path_set
            ):
                continue

            if before is not None:
                continue

            if not isinstance(
                after,
                str,
            ):
                continue

        elif change_type == "delete":

            if (
                file_path
                not in repository_file_map
            ):
                continue

            if not isinstance(
                before,
                str,
            ):
                continue

            if after is not None:
                continue

        else:
            continue

        change.pop(
            "_unverified_versions",
            None,
        )

        change.pop(
            "_unverified_github_shas",
            None,
        )

        change.pop(
            "_run_as_non_root_requires_verification",
            None,
        )

        executable_changes.append(
            change
        )

    result[
        "changes"
    ] = executable_changes

    result[
        "change_count"
    ] = len(
        executable_changes
    )

    return result